apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/green

# Adds a prefix or namespace specific to Cluster-A
namespace: green-namespace
namePrefix: cluster-b-

# Built-in image tag management
images:
  - name: nginx           # This must match the 'image' name used in your base deployment
    newName: my-registry/blue-app
    newTag: v1

patches:
  - target:
      kind: Service
      name: green-service
    patch: |-
      - op: replace
        path: /spec/ports/0/port
        value: 8083
      - op: replace
        path: /spec/type
        value: LoadBalancer