apiVersion: apps/v1
kind: Deployment
metadata:
  name: charcoal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charcoal
  template:
    metadata:
      labels:
        app: charcoal
    spec:
      containers:
      - name: main
        image: nginx:latest # Placeholder image
        ports:
        - containerPort: 80