apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-cluster-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/miriam-sandbox/Kustomize_Terraform_ArgoCD_K8S_Deployment_QR.git'
    path: manifests-ArgoCD/Cluster-B/overlays/green
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: green-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true